[package]
name = "fiberhome-factory"
version = "0.1.0"
edition = "2024"
license = "GPL-2.0-only"

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow"] }
rfd = "0.17.2"
fontdb = "0.23"
getrandom = "0.3"
flate2 = "1"
lzokay-native = { version = "0.1", default-features = false, features = ["decompress"] }
tempfile = "3"
ttf-parser = "0.25"

[features]
linux-x11 = ["eframe/x11"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"
